version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qnm-opensoho_server_1
      APP_PORT: 8090

  server:
    image: ghcr.io/opensoho/opensoho:v0.10.2
    command: >
      sh -c "./opensoho superuser upsert admin@opensoho.local \"$$APP_PASSWORD\" &&
             ./opensoho serve --http 0.0.0.0:8090"
    init: true
    restart: on-failure
    environment:
      OPENSOHO_SHARED_SECRET: $APP_PASSWORD
      APP_PASSWORD: $APP_PASSWORD
    volumes:
      - ${APP_DATA_DIR}/data/pb_data:/ko-app/pb_data
